### PR TITLE
ENH: fixed scoping of symbols of keywords closes #27

### LINKED ISSUE #27: Some symbols are highlighted as keywords
e.g. `:type`.

### PR DESCRIPTION
**Pull request by spencerlyon2**
Should fix #27.

Now that we have a few sets of eyes on the package I'll let someone else merge if it looks ok to them.

### CODE REVIEW

**Comment by garborg** [comment]
`type!` is still highlighted as `keyword`+`operator` when in reality it's a name. Included changes look good.

**Comment by garborg** [comment]
Maybe add this repo to those covered by the Contributors group? I'd merge this (and add the `type!` change to the PR I'm working on), but I don't have permissions.

**Comment by spencerlyon2** [comment]
@johnmyleswhite: Can you either give write access to all contributors or  give @garborg  push rights to the repo? Thanks

**Comment by johnmyleswhite** [comment]
Working on it

**Comment by johnmyleswhite** [comment]
Contributors should have access to this repo now

**Comment by garborg** [comment]
Thanks!

**Pull request merged**
