### PR TITLE
Remove latex snippets

### PR DESCRIPTION
**Pull request by one-more-minute**
LaTeX completion is a useful feature outside of (and somewhat orthogonal to) editing Julia code. I think it's best to separate concerns here and encourage people to use a separate package for LaTeX completions (such as [this one](https://github.com/JunoLab/atom-latex-completions)).

### CODE REVIEW

**Comment by spencerlyon2** [comment]
I'm on board with this, but I'd also like to not lose the emoji too .

It doesn't really belong in your new latex completions package, but I don't know that there is a better home than there or here. 

There is [this](https://atom.io/packages/autocomplete-emojis) emoji package, but it won't work in the `source.julia` scope and the completions won't match the Julia REPL exactly (like the current file here).

Any suggestions?

**Comment by one-more-minute** [comment]
I wouldn't be completely against adding Julia's emoji's to latex-completions as an option, although if there's an existing package it'd be a lot better to use that. Not having exact parity with the REPL seems like a relatively minor disadvantage. (Weren't they basically only added as an Easter egg anyway? Apart from OS X they're generally not supported well at all.)

I imagine it wouldn't be too hard to add an option to customise the scope of the emoji package (latex-completions needs this anyway). Do you definitely want to keep the completions in place in the mean time?

**Comment by spencerlyon2** [comment]
That sounds good. 

Will you also add a note in this readme that tells users to look in the latex-completions package if they want REPL style unicode latex? I'll merge after we have that note

**Comment by one-more-minute** [comment]
How's that? I've added a new section so that we can add other extras as they come along.

**Comment by spencerlyon2** [comment]
Great, will merge on the green light

**Comment by spencerlyon2** [comment]
Ha, forgot that this doesn't change anything testable. Merging now. Thanks @one-more-minute

**Comment by one-more-minute** [comment]
Thank you, @spencerlyon2

**Pull request merged**
