### PR TITLE
"Fix" improper highlighting of arrays as types

### LINKED ISSUE #41: BUG: currently indexing an array thinks the array is a type
In 

```
xs[i]
```

we would have that `xs` is scoped as a type. I can think of a few instances where we want this to be a type:

- `Float64[]` -- creating an empty, typed array
- `Float64[1, 2, 3]` -- creating a non-empty, typed array
- `Float64[f(i) for i in x]`-- typed comprehension

Not sure how we separate case 2 and indexing...

Maybe we just wait until when (if?) Jeff wins and we moved the type for typed comprehensions/arrays to the end (e.g. `[...]T` instead of the current `T[...]`)

### PR DESCRIPTION
**Pull request by pfitzseb**
Though I'm not sure this doesn't break anything else -- all these regexps are a bit much...

Fixes #41.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Any chance you'd be up for fixing the failing tests here?

**Comment by pfitzseb** [comment]
Oh right... specs pass locally now.

**Comment by pfitzseb** [comment]
You're way too fast for me ;)
#79 would be the better fix for the specs...

**Comment by spencerlyon2** [comment]
Thanks!

**Comment by jianghaizhu** [comment]
@spencerlyon2 Could you tag a new version for this fix? Thanks.

**Comment by spencerlyon2** [comment]
done: https://atom.io/packages/language-julia

**Comment by jianghaizhu** [comment]
@spencerlyon2 Thanks a lot!

**Pull request merged**
