### PR TITLE
Fix mismatched parentheses

### PR DESCRIPTION
**Pull request by Libbum**
Fixes issue #46

The `do|else` etc group was missing its opening parenthesis.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Thanks!

**Comment by MichaelHatherly** [comment]
After updating I've been getting an `Uncaught Error: end pattern with unmatched parenthesis` error message that is being caused by this change.

The `\\)` part of the regex is an escaped `)` rather than the end of a group, which appears to be what caused the mismatched highlighting in regexpal mentioned in #46. The `do|else...` is not a separate group as far as I can see.

---

For reference here's the full error message. Note this also happens on `stable` Atom, not just `beta`.

**Atom Version**: 1.3.0-beta1
**System**: linux 4.2.5-1-ARCH
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: end pattern with unmatched parenthesis

```
At /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:803

Error: end pattern with unmatched parenthesis
    at Error (native)
    at new OnigRegExp (/usr/share/atom-beta/resources/app.asar/node_modules/oniguruma/lib/onig-reg-exp.js:9:22)
    at LanguageMode.module.exports.LanguageMode.getRegexForProperty (/usr/share/atom-beta/resources/app.asar/src/language-mode.js:410:16)
    at LanguageMode.module.exports.LanguageMode.increaseIndentRegexForScopeDescriptor (/usr/share/atom-beta/resources/app.asar/src/language-mode.js:415:19)
    at LanguageMode.module.exports.LanguageMode.suggestedIndentForTokenizedLineAtBufferRow (/usr/share/atom-beta/resources/app.asar/src/language-mode.js:304:34)
    at LanguageMode.module.exports.LanguageMode.suggestedIndentForBufferRow (/usr/share/atom-beta/resources/app.asar/src/language-mode.js:288:19)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/usr/share/atom-beta/resources/app.asar/src/language-mode.js:366:26)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (/usr/share/atom-beta/resources/app.asar/src/text-editor.js:3066:32)
    at Selection.module.exports.Selection.insertText (/usr/share/atom-beta/resources/app.asar/src/selection.js:498:21)
    at /usr/share/atom-beta/resources/app.asar/src/text-editor.js:775:29
```

### Commands

```
     -0:02.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "archive-view",
      "autocomplete-css",
      "autocomplete-html",
      "autocomplete-snippets",
      "background-tips",
      "bookmarks",
      "image-view",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-javascript",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "language-xml",
      "metrics",
      "open-on-github",
      "welcome",
      "exception-reporting",
      "vim-mode",
      "julia-client",
      "ink",
      "indent-detective"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Office Code Pro",
    "fontSize": 12,
    "preferredLineLength": 92,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "showInvisibles": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
language-julia, v0.4.1

# Dev
No dev packages
```

**Comment by Libbum** [comment]
Hmm. I'll take another look at it soon.

**Comment by MichaelHatherly** [comment]
Thanks @Libbum.

**Comment by spencerlyon2** [comment]
Sorry, I should have tested more carefully before merging. 

I think this is a real issue. The original regex was a [valid regex](https://regex101.com/r/sZ2wS6/6) whereas the new one [is not](https://regex101.com/r/sZ2wS6/7)

That isn't to say the original pattern is actually what we want, but at least it is not a "malformed expression"

**Comment by Libbum** [comment]
Alright. So let's chock this up to being my first ever pull request and it ultimately being a failure. 

So in that case, the question is: was #46 an actual problem with the expression, or with the parser on regexpal.com? Judging by the regex101 tests @spencerlyon2 just did it seems like the latter. For now, I suggest we revert this commit; as the original issue stated the regex wasn't in error, just that it seemed to parse incorrectly.

**Comment by spencerlyon2** [comment]
@Libbum no problem, it was a failure on my end for not testing before merging. Thanks for contributing!

My hunch is that maybe we pasted in the raw regex (as it appears in language-julia.cson) into the parser and it had a hard time with all the `\\` double escape characters.

I also agree that we can simply revert back to the original version, I'll do this now.

**Comment by spencerlyon2** [comment]
Done in d8697c10107a8ecdf02c254984ba54627279d208

**Comment by MichaelHatherly** [comment]
Thanks, working fine now.

**Pull request merged**
