### PR TITLE
Add highlighting for Cxx.jl string macros

### PR DESCRIPTION
**Pull request by Keno**
Please check if this looks reasonable.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
Looks good. Could you add a spec (test) to make sure you are getting the scopes you expect?

**Comment by Keno** [comment]
Done, though ideally I wanted it to recurse into the C++ scope and tokenize that as well to make sure that's happening correctly too, but that didn't seem to be happening.

**Comment by spencerlyon2** [comment]
Thanks. That's exactly what I was hoping the spec would help us learn... I'll take a look pretty soon and see if we can get it to tokenize  into the c++ scopes.

**Comment by spencerlyon2** [comment]
Sorry, I haven't had time to take a look at this yet. Hopefully later tonight...

**Comment by Keno** [comment]
If we can't figure it out soon, can we merge this in the meantime. It does have some tests and I'll notice when it break ;).

**Comment by spencerlyon2** [comment]
Yep good call. The work here seems correct to me, if the scopes aren't coming through it is probably an issue with atom. 

I'll merge.

**Comment by Keno** [comment]
Can we have a new release with this included?

**Comment by spencerlyon2** [comment]
done!

**Comment by Keno** [comment]
Thanks!

**Pull request merged**
